-- One ranking row per game seed. Applied the same way as the earlier
-- migrations: via `wrangler d1 migrations apply qixxx-scores` — locally
-- against wrangler's local D1 emulation during development, against the real
-- D1 database only after the pre-check in docs/ranking-audit-runbook.md §2.2.
-- Additive-only: no column or index is dropped or renamed.
--
-- Why a UNIQUE index on `seed` alone:
-- - A normal run's seed is 32 bits of crypto.getRandomValues() output drawn
-- fresh for every run (src/main.ts's generateNormalRunSeed()), so two
-- honest runs share a seed with probability 2^-32 per pair. Seeded
-- (`?seed=`) runs are never submitted at all.
-- - A replay served by GET /api/ranking/:id/replay carries its seed. The
-- existing `replay_hash` index only refuses the byte-identical input
-- stream, so one changed input sample near the end of a copied replay
-- used to yield a fresh hash under the same seed — a second, "new" row
-- reproducing somebody else's run. Refusing a second row per seed closes
-- that path at INSERT time.
-- - What this does NOT close: a copy under a different seed that happens
-- to yield the same per-stage rng streams. deriveStageSeed() (src/core/
-- rng.ts) is FNV-1a over "<seed>:<stage>", so two seeds whose hash state
-- agrees after "<seed>:" collide on every stage (e.g. 1485211075 and
-- 2522981067); the copied inputs then pass the audit under the new seed
-- with a new replay_hash. Recorded as a known limitation in
-- docs/ranking-runbook.md §6 until replay identity is derived from the
-- effective rng streams rather than the numeric seed.
-- - Not scoped to season_id: an old season's replay is still a copy, and a
-- seed is never legitimately reused across seasons either.
--
-- A violation surfaces as the same SQLite UNIQUE error POST /api/scores
-- already maps to 409 "duplicate replay" (functions/api/scores.ts's
-- isUniqueConstraintViolation()).
CREATE UNIQUE INDEX idx_scores_seed ON scores(seed);
